# -*- coding: utf-8 -*-
"""nerComparison.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HNzvCW_T7qW9Zfqib1tM_2kJS8uLpf-B
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('/content/allComparisonFinal2.csv')
df

sns.displot(data=df, x="Real", kind="kde")

g = sns.displot(data=df, x="all ", y="Model")
g.figure.set_figwidth(10)
g.figure.set_figheight(10)
g.set(xlabel='Named Entity Count', ylabel='Model')

k = sns.displot(data=df, x="all ", y="Real", hue="Model", kind="kde")
k.figure.set_figwidth(8)
k.figure.set_figheight(8)
k.set(xlabel='Named Entity Count identified by models', ylabel='Real Named Entity Count')

import matplotlib.pyplot as plt
sns.set(style='darkgrid')
labels = ['person', 'location', 'organization', 'misc', 'all ']
for i, label in enumerate(labels):
    plt.figure(figsize=(8, 6))
    sns.displot(df, x='all ', hue='Real', kind='kde', fill=True)
    plt.title(f"Distribution of '{label}' entities identified by NER models")
    plt.xlabel('Number of entities')
    plt.legend(title='Real', labels=['True', 'False'])
    plt.show()

g = sns.jointplot(df, x="person ", y="all ", hue="Model")
g.figure.set_figwidth(13)
g.figure.set_figheight(13)
g.ax_marg_x.set_xlim(0, None)
g.ax_marg_y.set_ylim(0, None)
g.set_axis_labels('Named Entity Count (Person)', 'Named Entity Count (All)', fontsize=16)

g = sns.jointplot(df, x="person ", y="Real", hue="Model")
g.figure.set_figwidth(13)
g.figure.set_figheight(13)
g.ax_marg_x.set_xlim(0, None)
g.ax_marg_y.set_ylim(0, None)
g.set_axis_labels('Named Entity Count (Person)', 'Named Entity Count (All)', fontsize=16)

f = sns.jointplot(df, x="person ", y="all ", hue="Source")
f.figure.set_figwidth(13)
f.figure.set_figheight(13)
f.ax_marg_x.set_xlim(0, None)
f.ax_marg_y.set_ylim(0, None)
f.set_axis_labels('Named Entity Count (Person)', 'Named Entity Count (All)', fontsize=16)