# -*- coding: utf-8 -*-
"""saveToDrive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Gvol9WB6h27visnrPYfECY2XFxj5FGu
"""

!git lfs install
!git clone https://huggingface.co/bigscience/bloom-7b1

from google.colab import drive
drive.mount('/content/drive')

src_path = '/content/bloom-7b1'
dest_path = '/content/drive/MyDrive/AI/models'
!cp -r $src_path $dest_path